/**
 * countryData.ts
 * 
 * This file contains a static mapping of ISO A2 country codes to their full names
 * and geographical regions. It also provides utility functions for extracting
 * ISO codes from GeoJSON properties with fallback mechanisms.
 */

export const COUNTRY_DATA: Record<string, { name: string; region: string }> = {
  AF: { name: "Afghanistan", region: "Asia" },
  AL: { name: "Albania", region: "Europe" },
  DZ: { name: "Algeria", region: "Africa" },
  AS: { name: "American Samoa", region: "Oceania" },
  AD: { name: "Andorra", region: "Europe" },
  AO: { name: "Angola", region: "Africa" },
  AI: { name: "Anguilla", region: "Americas" },
  AQ: { name: "Antarctica", region: "Antarctic" },
  AG: { name: "Antigua and Barbuda", region: "Americas" },
  AR: { name: "Argentina", region: "Americas" },
  AM: { name: "Armenia", region: "Asia" },
  AW: { name: "Aruba", region: "Americas" },
  AU: { name: "Australia", region: "Oceania" },
  AT: { name: "Austria", region: "Europe" },
  AZ: { name: "Azerbaijan", region: "Asia" },
  BS: { name: "Bahamas", region: "Americas" },
  BH: { name: "Bahrain", region: "Asia" },
  BD: { name: "Bangladesh", region: "Asia" },
  BB: { name: "Barbados", region: "Americas" },
  BY: { name: "Belarus", region: "Europe" },
  BE: { name: "Belgium", region: "Europe" },
  BZ: { name: "Belize", region: "Americas" },
  BJ: { name: "Benin", region: "Africa" },
  BM: { name: "Bermuda", region: "Americas" },
  BT: { name: "Bhutan", region: "Asia" },
  BO: { name: "Bolivia", region: "Americas" },
  BA: { name: "Bosnia and Herzegovina", region: "Europe" },
  BW: { name: "Botswana", region: "Africa" },
  BR: { name: "Brazil", region: "Americas" },
  BN: { name: "Brunei", region: "Asia" },
  BG: { name: "Bulgaria", region: "Europe" },
  BF: { name: "Burkina Faso", region: "Africa" },
  BI: { name: "Burundi", region: "Africa" },
  KH: { name: "Cambodia", region: "Asia" },
  CM: { name: "Cameroon", region: "Africa" },
  CA: { name: "Canada", region: "Americas" },
  CV: { name: "Cape Verde", region: "Africa" },
  KY: { name: "Cayman Islands", region: "Americas" },
  CF: { name: "Central African Republic", region: "Africa" },
  TD: { name: "Chad", region: "Africa" },
  CL: { name: "Chile", region: "Americas" },
  CN: { name: "China", region: "Asia" },
  CO: { name: "Colombia", region: "Americas" },
  KM: { name: "Comoros", region: "Africa" },
  CG: { name: "Congo", region: "Africa" },
  CD: { name: "Congo, Democratic Republic", region: "Africa" },
  CR: { name: "Costa Rica", region: "Americas" },
  CI: { name: "Cote d'Ivoire", region: "Africa" },
  HR: { name: "Croatia", region: "Europe" },
  CU: { name: "Cuba", region: "Americas" },
  CY: { name: "Cyprus", region: "Asia" },
  CZ: { name: "Czech Republic", region: "Europe" },
  DK: { name: "Denmark", region: "Europe" },
  DJ: { name: "Djibouti", region: "Africa" },
  DM: { name: "Dominica", region: "Americas" },
  DO: { name: "Dominican Republic", region: "Americas" },
  EC: { name: "Ecuador", region: "Americas" },
  EG: { name: "Egypt", region: "Africa" },
  SV: { name: "El Salvador", region: "Americas" },
  GQ: { name: "Equatorial Guinea", region: "Africa" },
  ER: { name: "Eritrea", region: "Africa" },
  EE: { name: "Estonia", region: "Europe" },
  ET: { name: "Ethiopia", region: "Africa" },
  FJ: { name: "Fiji", region: "Oceania" },
  FI: { name: "Finland", region: "Europe" },
  FR: { name: "France", region: "Europe" },
  GA: { name: "Gabon", region: "Africa" },
  GM: { name: "Gambia", region: "Africa" },
  GE: { name: "Georgia", region: "Asia" },
  DE: { name: "Germany", region: "Europe" },
  GH: { name: "Ghana", region: "Africa" },
  GR: { name: "Greece", region: "Europe" },
  GD: { name: "Grenada", region: "Americas" },
  GU: { name: "Guam", region: "Oceania" },
  GT: { name: "Guatemala", region: "Americas" },
  GN: { name: "Guinea", region: "Africa" },
  GW: { name: "Guinea-Bissau", region: "Africa" },
  GY: { name: "Guyana", region: "Americas" },
  HT: { name: "Haiti", region: "Americas" },
  HN: { name: "Honduras", region: "Americas" },
  HK: { name: "Hong Kong", region: "Asia" },
  HU: { name: "Hungary", region: "Europe" },
  IS: { name: "Iceland", region: "Europe" },
  IN: { name: "India", region: "Asia" },
  ID: { name: "Indonesia", region: "Asia" },
  IR: { name: "Iran", region: "Middle East" },
  IQ: { name: "Iraq", region: "Middle East" },
  IE: { name: "Ireland", region: "Europe" },
  IL: { name: "Israel", region: "Middle East" },
  IT: { name: "Italy", region: "Europe" },
  JM: { name: "Jamaica", region: "Americas" },
  JP: { name: "Japan", region: "Asia" },
  JO: { name: "Jordan", region: "Middle East" },
  KZ: { name: "Kazakhstan", region: "Asia" },
  KE: { name: "Kenya", region: "Africa" },
  KI: { name: "Kiribati", region: "Oceania" },
  KP: { name: "North Korea", region: "Asia" },
  KR: { name: "South Korea", region: "Asia" },
  KW: { name: "Kuwait", region: "Middle East" },
  KG: { name: "Kyrgyzstan", region: "Asia" },
  LA: { name: "Laos", region: "Asia" },
  LV: { name: "Latvia", region: "Europe" },
  LB: { name: "Lebanon", region: "Middle East" },
  LS: { name: "Lesotho", region: "Africa" },
  LR: { name: "Liberia", region: "Africa" },
  LY: { name: "Libya", region: "Africa" },
  LI: { name: "Liechtenstein", region: "Europe" },
  LT: { name: "Lithuania", region: "Europe" },
  LU: { name: "Luxembourg", region: "Europe" },
  MO: { name: "Macao", region: "Asia" },
  MK: { name: "Macedonia", region: "Europe" },
  MG: { name: "Madagascar", region: "Africa" },
  MW: { name: "Malawi", region: "Africa" },
  MY: { name: "Malaysia", region: "Asia" },
  MV: { name: "Maldives", region: "Asia" },
  ML: { name: "Mali", region: "Africa" },
  MT: { name: "Malta", region: "Europe" },
  MH: { name: "Marshall Islands", region: "Oceania" },
  MQ: { name: "Martinique", region: "Americas" },
  MR: { name: "Mauritania", region: "Africa" },
  MU: { name: "Mauritius", region: "Africa" },
  MX: { name: "Mexico", region: "Americas" },
  FM: { name: "Micronesia", region: "Oceania" },
  MD: { name: "Moldova", region: "Europe" },
  MC: { name: "Monaco", region: "Europe" },
  MN: { name: "Mongolia", region: "Asia" },
  ME: { name: "Montenegro", region: "Europe" },
  MS: { name: "Montserrat", region: "Americas" },
  MA: { name: "Morocco", region: "Africa" },
  MZ: { name: "Mozambique", region: "Africa" },
  MM: { name: "Myanmar", region: "Asia" },
  NA: { name: "Namibia", region: "Africa" },
  NR: { name: "Nauru", region: "Oceania" },
  NP: { name: "Nepal", region: "Asia" },
  NL: { name: "Netherlands", region: "Europe" },
  NZ: { name: "New Zealand", region: "Oceania" },
  NI: { name: "Nicaragua", region: "Americas" },
  NE: { name: "Niger", region: "Africa" },
  NG: { name: "Nigeria", region: "Africa" },
  NU: { name: "Niue", region: "Oceania" },
  NF: { name: "Norfolk Island", region: "Oceania" },
  MP: { name: "Northern Mariana Islands", region: "Oceania" },
  NO: { name: "Norway", region: "Europe" },
  OM: { name: "Oman", region: "Middle East" },
  PK: { name: "Pakistan", region: "Asia" },
  PW: { name: "Palau", region: "Oceania" },
  PS: { name: "Palestine", region: "Middle East" },
  PA: { name: "Panama", region: "Americas" },
  PG: { name: "Papua New Guinea", region: "Oceania" },
  PY: { name: "Paraguay", region: "Americas" },
  PE: { name: "Peru", region: "Americas" },
  PH: { name: "Philippines", region: "Asia" },
  PN: { name: "Pitcairn", region: "Oceania" },
  PL: { name: "Poland", region: "Europe" },
  PT: { name: "Portugal", region: "Europe" },
  PR: { name: "Puerto Rico", region: "Americas" },
  QA: { name: "Qatar", region: "Middle East" },
  RE: { name: "Reunion", region: "Africa" },
  RO: { name: "Romania", region: "Europe" },
  RU: { name: "Russia", region: "Europe" },
  RW: { name: "Rwanda", region: "Africa" },
  SH: { name: "Saint Helena", region: "Africa" },
  KN: { name: "Saint Kitts and Nevis", region: "Americas" },
  LC: { name: "Saint Lucia", region: "Americas" },
  PM: { name: "Saint Pierre and Miquelon", region: "Americas" },
  VC: { name: "Saint Vincent and the Grenadines", region: "Americas" },
  WS: { name: "Samoa", region: "Oceania" },
  SM: { name: "San Marino", region: "Europe" },
  ST: { name: "Sao Tome and Principe", region: "Africa" },
  SA: { name: "Saudi Arabia", region: "Middle East" },
  SN: { name: "Senegal", region: "Africa" },
  RS: { name: "Serbia", region: "Europe" },
  SC: { name: "Seychelles", region: "Africa" },
  SL: { name: "Sierra Leone", region: "Africa" },
  SG: { name: "Singapore", region: "Asia" },
  SK: { name: "Slovakia", region: "Europe" },
  SI: { name: "Slovenia", region: "Europe" },
  SB: { name: "Solomon Islands", region: "Oceania" },
  SO: { name: "Somalia", region: "Africa" },
  ZA: { name: "South Africa", region: "Africa" },
  GS: { name: "South Georgia and the South Sandwich Islands", region: "Antarctic" },
  ES: { name: "Spain", region: "Europe" },
  LK: { name: "Sri Lanka", region: "Asia" },
  SD: { name: "Sudan", region: "Africa" },
  SR: { name: "Suriname", region: "Americas" },
  SJ: { name: "Svalbard and Jan Mayen", region: "Europe" },
  SZ: { name: "Swaziland", region: "Africa" },
  SE: { name: "Sweden", region: "Europe" },
  CH: { name: "Switzerland", region: "Europe" },
  SY: { name: "Syria", region: "Middle East" },
  TW: { name: "Taiwan", region: "Asia" },
  TJ: { name: "Tajikistan", region: "Asia" },
  TZ: { name: "Tanzania", region: "Africa" },
  TH: { name: "Thailand", region: "Asia" },
  TL: { name: "Timor-Leste", region: "Asia" },
  TG: { name: "Togo", region: "Africa" },
  TK: { name: "Tokelau", region: "Oceania" },
  TO: { name: "Tonga", region: "Oceania" },
  TT: { name: "Trinidad and Tobago", region: "Americas" },
  TN: { name: "Tunisia", region: "Africa" },
  TR: { name: "Turkey", region: "Europe" },
  TM: { name: "Turkmenistan", region: "Asia" },
  TC: { name: "Turks and Caicos Islands", region: "Americas" },
  TV: { name: "Tuvalu", region: "Oceania" },
  UG: { name: "Uganda", region: "Africa" },
  UA: { name: "Ukraine", region: "Europe" },
  AE: { name: "United Arab Emirates", region: "Middle East" },
  GB: { name: "United Kingdom", region: "Europe" },
  US: { name: "United States", region: "Americas" },
  UM: { name: "United States Minor Outlying Islands", region: "Oceania" },
  UY: { name: "Uruguay", region: "Americas" },
  UZ: { name: "Uzbekistan", region: "Asia" },
  VU: { name: "Vanuatu", region: "Oceania" },
  VE: { name: "Venezuela", region: "Americas" },
  VN: { name: "Vietnam", region: "Asia" },
  VG: { name: "Virgin Islands, British", region: "Americas" },
  VI: { name: "Virgin Islands, U.S.", region: "Americas" },
  WF: { name: "Wallis and Futuna", region: "Oceania" },
  EH: { name: "Western Sahara", region: "Africa" },
  YE: { name: "Yemen", region: "Middle East" },
  ZM: { name: "Zambia", region: "Africa" },
  ZW: { name: "Zimbabwe", region: "Africa" },
};

// --- Types & Interfaces ---

export interface GeoJsonProperties {
  ISO_A2?: string;
  NAME?: string;
  [key: string]: unknown; // Allows for arbitrary GeoJSON props safely
}

// --- Pre-computed Constants ---

// Fallback map for Natural Earth's "-99" cases or missing ISO_A2
const FALLBACK_NAME_MAP: Record<string, string> = {
  France: "FR",
  Norway: "NO",
  Somaliland: "SO",
  Kosovo: "XK",
  "N. Cyprus": "CY",
  Tonga: "TO",
} as const;

// O(1) Reverse lookup map constructed once at initialization
const COUNTRY_NAME_TO_CODE = new Map<string, string>();
for (const [code, data] of Object.entries(COUNTRY_DATA)) {
  COUNTRY_NAME_TO_CODE.set(data.name.toLowerCase(), code);
}

// --- Main Processor ---

/**
 * Extracts the ISO A2 country code from GeoJSON feature properties.
 */
export function getIsoA2FromGeoJson(properties?: GeoJsonProperties | null): string | null {
  if (!properties) return null;

  // 1. Direct ISO_A2 match (excluding Natural Earth's -99 missing data code)
  if (properties.ISO_A2 && properties.ISO_A2 !== "-99") {
    return properties.ISO_A2;
  }

  // 2. Name-based fallbacks
  if (properties.NAME) {
    const hardcodedMatch = FALLBACK_NAME_MAP[properties.NAME];
    if (hardcodedMatch) return hardcodedMatch;

    const dynamicMatch = COUNTRY_NAME_TO_CODE.get(properties.NAME.toLowerCase());
    if (dynamicMatch) return dynamicMatch;
  }

  return null;
}