# Module Definition Properties
module_name=[NWC] Bandwidth Utilization Deviation
module_desc=Detects if an IP is communicating outbound with an hourly volume that deviates from previous behaviors on the same hour of the same day of the week.
module_desc_long=Continuously learns the bandwidth utilization for IPs communicating outbound. Compares the current hourly utilization with the average utilization on that same hour of the same day of the week from the past 4 weeks and generates an alert if it increased significantly.

# FTL Template Variables
ip_list_name=List of source IP addresses to whitelist
ip_list_desc=List of source IP addresses to whitelist
